### ISSUE TITLE
win64, selenium + Python 2.6.6 win32 - can't start

### ISSUE THREAD

**Issue by oppapaa** [laurentj/slimerjs#625]
### versions 

- SlimerJS: slimerjs-0.10.3 / slimerjs-0.9.6-win32.zip with the same result
- Firefox: Mozilla Firefox v50 win32
- Operating system: windows7, win64
- Python: Python 2.6.6 (r266:84297, Aug 24 2010, 18:46:32) [MSC v.1500 32 bit (Intel)] on win32

### Steps to reproduce the issue
I want to use SlimerJS with python + selenium:
```
	from selenium import webdriver

	f = r'c:\slimerjs'

	driver = webdriver.PhantomJS(executable_path=f)
	driver.set_window_size(1280,1024)
	driver.get('https://slimerjs.org')
	driver.save_screenshot('temp/screenie.png')

```

### Actual results:
Traceback (most recent call last):
  File "bet365.py", line 10392, in <module>
    test_slimer()
  File "bet365.py", line 10349, in test_slimer
    driver = webdriver.PhantomJS(executable_path=f)
  File "d:\server\usr\local\python\lib\site-packages\selenium-2.53.2-py2.6.egg\selenium\webdriver\phantomjs\webdriver.py", line 51, in __init__
    self.service.start()
  File "d:\server\usr\local\python\lib\site-packages\selenium-2.53.2-py2.6.egg\selenium\webdriver\common\service.py", line 62, in start
    stdout=self.log_file, stderr=self.log_file)
  File "d:\server\usr\local\python\lib\subprocess.py", line 623, in __init__
    errread, errwrite)
  File "d:\server\usr\local\python\lib\subprocess.py", line 833, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 эх  ты хЄё  яЁшыюцхэшхь Win32
Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.phantomjs.service.Serv
ice object at 0x05C47C10>> ignored

### Expected results:
It should be screenshot :)

**Comment by oppapaa** [comment]
I have some progress :)

The problem was with wrong path. I was sure that I just should use only file slimerjs, that's why I used line
`	f = r'c:\slimerjs'
`
in my code.

But after I've mode full directory c:\slimerjs-0.10.3\ and changed line to
`		f = r'c:\slimerjs-0.10.3\slimerjs.bat'
`
, I could start slimerjs from command line, like
`slimerjs.bat test.js
`
In fact code from test.js runs successfully.

But I still have a problem with selenium. When I try to use it from selenium with code
```
from selenium import webdriver

f = r'c:\slimerjs-0.10.3\slimerjs.bat'

driver = webdriver.PhantomJS(executable_path=f)
driver.set_window_size(1280,1024)
driver.get('https://slimerjs.org')
driver.save_screenshot('screenie.png')

```
I get an error
```
c:\slimerjs-0.10.3>minimum.py
Traceback (most recent call last):
  File "C:\slimerjs-0.10.3\minimum.py", line 5, in <module>
    driver = webdriver.PhantomJS(executable_path=f)
  File "D:\server\usr\local\python\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py", line 52, in __init__
    self.service.start()
  File "D:\server\usr\local\python\lib\site-packages\selenium\webdriver\common\service.py", line 96, in start
    self.assert_process_still_running()
  File "D:\server\usr\local\python\lib\site-packages\selenium\webdriver\common\service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service c:\slimerjs-0.10.3\slimerjs.bat unexpectedly exited. Status code was: 0
```

Any ideas how to solve that?

**Comment by oppapaa** [comment]
And it's strange for me that I can't strart slimerjs like webdriver. 

```
c:\slimerjs-0.10.3>slimerjs.bat --webdriver=localhost:9000 --webdriver-engine=ghostdriver --debug=yes --error-log-file=slimerjs.log
unknown option --webdriver=localhost:9000

```

Is it ok?

**Comment by oppapaa** [comment]
I've setuped cygwin, and now able to work with real slimjs
This works, executes hello.js :
`bash slimerjs hello.js
`
But this 
`bash slimerjs --webdriver=localhost:9000 --webdriver-engine=ghostdriver --debug=yes --error-log-file=slimerjs.log`
still do nothings (something blinks in some miliseconds, and the script exits).

I've created my own slimerjs_my.bat with content
`bash slimerjs %*`
that redirects all arguments to real slimerjs. After that I can use
`slimerjs_my.bat hello.js
`
and it works.

But with selenium 
```
from selenium import webdriver

f = r'c:\slimerjs-0.10.3\slimerjs_my.bat'

driver = webdriver.PhantomJS(executable_path=f)
driver.set_window_size(1280,1024)
driver.get('https://slimerjs.org')
driver.save_screenshot('screenie.png')
```

I get an error 
c:\slimerjs-0.10.3>minimum.py
```
Traceback (most recent call last):
  File "C:\slimerjs-0.10.3\minimum.py", line 5, in <module>
    driver = webdriver.PhantomJS(executable_path=f)
  File "D:\server\usr\local\python\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py", line 52, in __init__
    self.service.start()
  File "D:\server\usr\local\python\lib\site-packages\selenium\webdriver\common\service.py", line 96, in start
    self.assert_process_still_running()
  File "D:\server\usr\local\python\lib\site-packages\selenium\webdriver\common\service.py", line 109, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service c:\slimerjs-0.10.3\slimerjs_my.bat unexpectedly exited. Status code was: 0
```
